apiVersion: v2
name: mirops
description: A Helm chart for mirops - Kubernetes Upgrade Analysis Operator
type: application
version: 0.6.0
appVersion: "0.6.0"
keywords:
  - kubernetes
  - operator
  - upgrade-analysis
maintainers:
  - name: Mirops Team
homepage: https://github.com/miropshq/mirops
