{{- if .Values.registryCredentials.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mirops.fullname" . }}-ghcr-secret
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "mirops.labels" . | nindent 4 }}
type: kubernetes.io/dockercfg
data:
  .dockercfg: {{ include "imagePullSecretData" . | b64enc }}
---
{{- end }}
