{{- if and .Values.reportPVC.enabled (not .Values.reportPVC.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "mirops.fullname" . }}-report
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "mirops.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- toYaml .Values.reportPVC.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.reportPVC.size }}
  {{- if .Values.reportPVC.storageClass }}
  storageClassName: {{ .Values.reportPVC.storageClass }}
  {{- end }}
{{- end }}
