replicaCount: 1

image:
  repository: ghcr.io/liveim/liveim
  tag: sha-28afb64
  pullPolicy: IfNotPresent

imagePullSecret:
  create: true
  name: ghcr-secret

  dockerconfigjson: ""

serviceAccount:
  create: true
  name: mirror-operator
  namespace: mirror

  aws:
    enabled: false
    roleArn: ""

  azure:
    enabled: false
    clientId: ""

namespace: mirror

labels:
  app: mirror-operator

rbac:
  create: true

  name: mirror-operator

  core:
    resources:
      - secrets
      - configmaps
      - pods
      - services
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete

  apps:
    resources:
      - deployments
      - replicasets
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete

  mirrorApi:
    apiGroup: mirror.mirror.dev
    resources:
      - namespacemirrors
      - namespacemirrors/status
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
