{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Values.serviceAccount.namespace }}
  annotations:
    {{- if and .Values.serviceAccount.aws.enabled .Values.serviceAccount.aws.roleArn }}
    eks.amazonaws.com/role-arn: {{ .Values.serviceAccount.aws.roleArn | quote }}
    {{- end }}

    {{- if and .Values.serviceAccount.azure.enabled .Values.serviceAccount.azure.clientId }}
    azure.workload.identity/client-id: {{ .Values.serviceAccount.azure.clientId | quote }}
    {{- end }}
{{- end }}
