name: Mirops Helm Chart CI Development Environment

on:
  push:
    branches:
      - development

permissions:
  contents: read
  packages: write

env:
  CHART_DIR: mirops-operator

jobs:
  validate:
    name: Lint and Validate Helm Chart
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: 'latest'
          
      - name: Helm template (render all manifests)
        working-directory: ${{ env.CHART_DIR }}
        run: helm template mirops . --debug > /dev/null

      - name: Helm template (render all manifests)
        working-directory: mirops-operator
        run: helm template mirops . --debug > /dev/null


  sync-crd:
    name: Download CRD from Mirops Repo
    runs-on: ubuntu-latest
    needs: validate

    steps:
      - name: Generate GitHub App token
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          repositories: mirops

      - name: Download CRD artifact
        uses: dawidd6/action-download-artifact@v9
        with:
          github_token: ${{ steps.app-token.outputs.token }}
          repo: miropshq/mirops
          workflow: ci-dev.yml
          branch: development
          name: crds-dev
          path: ./crds

      - name: Upload CRD artifact for next job
        uses: actions/upload-artifact@v4
        with:
          name: crds-dev
          path: ./crds/*.yaml
          retention-days: 1

  publish:
    name: Publish Helm Chart to OCI Registry
    runs-on: ubuntu-latest
    needs: sync-crd

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download CRD artifact
        uses: actions/download-artifact@v4
        with:
          name: crds-dev
          path: ${{ env.CHART_DIR }}/crds

      - name: Verify CRD files
        run: ls -lah ${{ env.CHART_DIR }}/crds

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: latest

      - name: Login to GitHub Container Registry
        run: |
          helm registry login ghcr.io \
            --username ${{ github.actor }} \
            --password ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Helm chart
        working-directory: ${{ env.CHART_DIR }}
        env:
          DEV_IMAGE_TAG: dev
        run: |
          CHART_VERSION=$(grep "^version:" Chart.yaml | awk '{print $2}')
          CHART_NAME="$(grep "^name:" Chart.yaml | awk '{print $2}')-dev"

          yq e ".name = \"${CHART_NAME}\"" -i Chart.yaml
          yq e ".image.tag = \"${DEV_IMAGE_TAG}\"" -i values.yaml
          yq e ".remediation.image.tag = \"${DEV_IMAGE_TAG}\"" -i values.yaml

          helm package .

          helm push ${CHART_NAME}-${CHART_VERSION}.tgz oci://ghcr.io/${{ github.repository_owner }}/charts

      - name: Logout from GitHub Container Registry
        if: always()
        run: helm registry logout ghcr.io
